export const Locations = {
    Amphitheater: 'Amphitheater',
    ApolinarioMabiniShrine: 'Apolinario Mabini Shrine',
    CharlieDelRosarioHall: 'Charlie Del Rosario Hall',
    EastWing1stFlr: 'East Wing 1st Floor',
    EastWing2ndFlr: 'East Wing 2nd Floor',
    EastWing3rdFlr: 'East Wing 3rd Floor',
    EastWing4thFlr: 'East Wing 4th Floor',
    EastWing5thFlr: 'East Wing 5th Floor',
    EastWing6thFlr: 'East Wing 6th Floor',
    FreedomPark: 'Freedom Park',
    Gazebo: 'Gazebo',
    Grandstand: 'Grandstand',
    GymnasiumAndSportsCenter: 'Gymnasium And Sports Center',
    InterfaithChapel: 'Interfaith Chapel',
    LaboratoryHighSchool: 'Laboratory High School',
    Lagoon: 'Lagoon',
    LinearPark: 'Linear Park',
    MabiniMonumentPupObelisk: 'Mabini Monument PUP Obelisk',
    NinoyAquinoLibraryAndLearningResourcesCenter: 'Ninoy Aquino Library And Learning Resources Center',
    NorthWing1stFlr: 'North Wing 1st Floor',
    NorthWing2ndFlr: 'North Wing 2nd Floor',
    NorthWing3rdFlr: 'North Wing 3rd Floor',
    NorthWing4thFlr: 'North Wing 4th Floor',
    NorthWing5thFlr: 'North Wing 5th Floor',
    NorthWing6thFlr: 'North Wing 6th Floor',
    OutdoorBasketballAndVolleyballCourt: 'Outdoor Basketball And Volleyball Court',
    PhysicalEducationBuilding: 'Physical Education Building',
    SouthWing1stFlr: 'South Wing 1st Floor',
    SouthWing2ndFlr: 'South Wing 2nd Floor',
    SouthWing3rdFlr: 'South Wing 3rd Floor',
    SouthWing4thFlr: 'South Wing 4th Floor',
    SouthWing5thFlr: 'South Wing 5th Floor',
    SouthWing6thFlr: 'South Wing 6th Floor',
    StudentCanteen: 'Student Canteen',
    SwimmingPool: 'Swimming Pool',
    TahananNgAlumni: 'Tahanan Ng Alumni',
    TennisCourt: 'Tennis Court',
    TrackAndFieldFootballOval: 'Track And Field Football Oval',
    UniversityCanteenSampaguitaBuilding: 'University Canteen Sampaguita Building',
    VisitorInformationCenter: 'Visitor Information Center',
    WestWing1stFlr: 'West Wing 1st Floor',
    WestWing2ndFlr: 'West Wing 2nd Floor',
    WestWing3rdFlr: 'West Wing 3rd Floor',
    WestWing4thFlr: 'West Wing 4th Floor',
    WestWing5thFlr: 'West Wing 5th Floor',
    WestWing6thFlr: 'West Wing 6th Floor',
    
};